### ISSUE TITLE
invalid Bing Number String

### ISSUE THREAD

**Issue by JPITH** [ahmedoubadi/front-running-bot#3]
reason: 'invalid BigNumber string',
code: 'INVALID_ARGUMENT',
argument: 'value',
value: '5.000000001'

th e returning this error after the execution of calculate maybe the error is in buy fonction because he says "prepare to buy" and returning this error

**Comment by dariobuzz** [comment]
I fixed with bigNumber

function calculate_gas_price(action, amount){
console.log("amount",amount);
if (action==="buy"){
const data=ethers.utils.formatUnits(amount.add(1000000000), 'wei')
return ethers.BigNumber.from(data.toString())

}else{

const data=ethers.utils.formatUnits(amount.sub(1000000000), 'wei')
return ethers.BigNumber.from(data.toString())
}
}
